config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  namespace :public do
    get 'genres/show'
  end
  get 'search' => 'searches#search'
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customer,skip: [:passwords,], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :items,except: [:destroy]
    resources :customers, except: [:destroy, :create, :new]
    resources :genres, except: [:destroy, :show, :new]
    get '/' => 'homes#top'
    resources:orders, only: [:index, :show, :update] do
      resources:order_items, only: [:update]
    end
  end

  scope module: :public do
    resources :customers, except: [:destroy]
    get '/' => 'homes#top'
    get '/about' => 'homes#about'
    resources :genres, only: [:show]
    patch 'unsubscribe' => 'customers#unsubscribe'
    get 'confirm' => 'customers#confirm'
    resources :items, only: [:index, :show]
    resources :cart_items, except: [:edit, :new, :show]
    delete 'destroy_all' => 'cart_items#destroy_all'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, except: [:destroy, :edit]
    resources :addresses, except: [:new, :show]
  end




end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    "〒" + self.post_code + " " + self.address + " " + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy

  validates :is_deleted, inclusion: { in: [true, false] }

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :genre_name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  attachment :image
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  belongs_to :genre


# 消費税の計算
  def add_tax_price
    (self.price * 1.1).round
  end

  # 検索機能
  def self.search(keyword)
    @items = Item.where("item_name LIKE ?", "%#{keyword}%")
  end


  validates :image, presence: true
  validates :item_name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  validates :is_status, presence: true

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: { wait: 0, check: 1, making: 2, prepare: 3, shipped: 4 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :item
  belongs_to :order

  enum sales_order_status: {
 impossible:0, wait:1, making:2, done:3
  }


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :telephone, :email, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def index
    @newgenres = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
    redirect_to admin_item_path(@item)
    else
    render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end


  private

  def item_params
    params.require(:item).permit(:genre_id, :item_name, :introduction, :price, :image, :is_status, )
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

    def index
        @orders = Order.page(params[:page]).per(10).order(created_at: 'DESC')
        # .order(created_at: 'DESC')降順に並び替え
    end

    def show
        @order = Order.find(params[:id])
        @order_items = OrderItem.all
    end

    def update
        @order = Order.find(params[:id])
        @order.update(order_params)
         if  @order.order_status == "check"
             @order.order_items.update_all(sales_order_status: OrderItem.sales_order_statuses[:wait])
         end
        redirect_to admin_order_path(@order)
    end

    private
    def order_params
        params.require(:order).permit(:customer_id, :freight, :payment_method, :ship_post_code, :ship_to_address, :ship_name, :total_due, :order_status)
    end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :telephone ])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @items = Item.search(params[:keyword])
    @keyword = params[:keyword]
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
    <div class="row">
        <h3 class="offset-1 my-4"><%= @customer.full_name %>さんの会員情報編集</h3>
        <%= form_with model:@customer,url: admin_customer_path(@customer.id), local:true do |f| %>
            <div class="row form-group">
                <div class="offset-1 col-3 mb-3">会員ID</div>
                <div class="col-8 mb-2"><%= @customer.id %></div>
                <div class="offset-1 col-3 mb-3"><%= f.label :氏名 %></div>
                <div class="col-4"><%= f.text_field :last_name, class: "form-control" %></div>
                <div class="col-4"><%= f.text_field :first_name, class: "form-control" %></div>
                <div class="offset-1 col-3 mb-3"><%= f.label :フリガナ %></div>
                <div class="col-4"><%= f.text_field :last_name_kana, class: "form-control" %></div>
                <div class="col-4"><%= f.text_field :first_name_kana, class: "form-control" %></div>
                <div class="offset-1 col-3 mb-3"><%= f.label :郵便番号 %></div>
                <div class="col-8"><%= f.text_field :post_code, class: "form-control" %></div>
                <div class="offset-1 col-3 mb-3"><%= f.label :住所 %></div>
                <div class="col-8"><%= f.text_field :address, class: "form-control" %></div>
                <div class="offset-1 col-3 mb-3"><%= f.label :電話番号 %></div>
                <div class="col-8"><%= f.text_field :telephone, class: "form-control" %></div>
                <div class="offset-1 col-3 mb-3"><%= f.label :メールアドレス %></div>
                <div class="col-8"><%= f.text_field :email, class: "form-control" %></div>
                <div class="offset-1 col-3 mb-3"><%= f.label :会員ステータス %></div>
                <%= f.radio_button :is_deleted, false, class: "custom-control custom-radio ml-3" %><%= f.label :有効, class: "pr-3" %>
                <%= f.radio_button :is_deleted, true, class: "custom-control custom-radio" %><%= f.label :退会 %>
                <div class="col-12"></div>
                <div class="offset-1 col-3 mb-3"></div>
                <%= f.submit "変更を保存", class: "btn btn-success ml-3" %>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <h3 class="my-3">会員一覧</h3>
      <table class="table table-hover">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.full_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
          <%if customer.is_deleted %>
              <p class="text-danger">退会</p>
          <% else %>
              <p class="text-success">有効</p>
          <% end %>
          </td>
        </tr>
      <% end %>
      </table>
    <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
    <div class="row">
        <h3 class="offset-2 col-10 my-4"><%= @customer.full_name %>さんの会員詳細</h3>
        <div class="col-3 offset-2 mb-2">会員ID</div>
        <div class="col-7 mb-2"><%= @customer.id %></div>
        <div class="col-3 offset-2 mb-2">氏名</div>
        <div class="col-7 mb-2"><%= @customer.full_name %></div>
        <div class="col-3 offset-2 mb-2">フリガナ</div>
        <div class="col-7 mb-2"><%= @customer.full_name_kana %></div>
        <div class="col-3 offset-2 mb-2">郵便番号</div>
        <div class="col-7 mb-2"><%= @customer.post_code %></div>
        <div class="col-3 offset-2 mb-2">住所</div>
        <div class="col-7 mb-2"><%= @customer.address %></div>
        <div class="col-3 offset-2 mb-2">電話番号</div>
        <div class="col-7 mb-2"><%= @customer.telephone %></div>
        <div class="col-3 offset-2 mb-2">メールアドレス</div>
        <div class="col-7 mb-2"><%= @customer.email %></div>
        <div class="col-3 offset-2 mb-2">会員ステータス</div>
        <div class="col-7 mb-2">
            <%if @customer.is_deleted %>
                <p class="text-danger">退会</p>
            <% else %>
                <p class="text-success">有効</p>
            <% end %>
        </div>
        <%= link_to "編集する",edit_admin_customer_path(@customer.id), class: "offset-2 btn btn-success" %>
        <%= link_to "注文履歴一覧を見る",admin_orders_path, class: "offset-2 btn btn-primary" %>
    </div>
</div>

app/views/customer/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>