config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  namespace :public do
    get 'genres/show'
  end
  get 'search' => 'searches#search'
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customer,skip: [:passwords,], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :items,except: [:destroy]
    resources :customers, except: [:destroy, :create, :new]
    resources :genres, except: [:destroy, :show, :new]
    get '/' => 'homes#top'
    resources:orders, only: [:index, :show, :update] do
      resources:order_items, only: [:update]
    end
  end

  scope module: :public do
    resources :customers, except: [:destroy]
    get '/' => 'homes#top'
    get '/about' => 'homes#about'
    resources :genres, only: [:show]
    patch 'unsubscribe' => 'customers#unsubscribe'
    get 'confirm' => 'customers#confirm'
    resources :items, only: [:index, :show]
    resources :cart_items, except: [:edit, :new, :show]
    delete 'destroy_all' => 'cart_items#destroy_all'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, except: [:destroy, :edit]
    resources :addresses, except: [:new, :show]
  end




end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    "〒" + self.post_code + " " + self.address + " " + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy

  validates :is_deleted, inclusion: { in: [true, false] }

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :genre_name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  attachment :image
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  belongs_to :genre


# 消費税の計算
  def add_tax_price
    (self.price * 1.1).round
  end

  # 検索機能
  def self.search(keyword)
    @items = Item.where("item_name LIKE ?", "%#{keyword}%")
  end


  validates :image, presence: true
  validates :item_name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  validates :is_status, presence: true

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: { wait: 0, check: 1, making: 2, prepare: 3, shipped: 4 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :item
  belongs_to :order

  enum sales_order_status: {
 impossible:0, wait:1, making:2, done:3
  }


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def index
    @newgenres = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
    redirect_to admin_item_path(@item)
    else
    render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end


  private

  def item_params
    params.require(:item).permit(:genre_id, :item_name, :introduction, :price, :image, :is_status, )
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

    def index
        @orders = Order.page(params[:page]).per(10).order(created_at: 'DESC')
        # .order(created_at: 'DESC')降順に並び替え
    end

    def show
        @order = Order.find(params[:id])
        @order_items = OrderItem.all
    end

    def update
        @order = Order.find(params[:id])
        @order.update(order_params)
         if  @order.order_status == "check"
             @order.order_items.update_all(sales_order_status: OrderItem.sales_order_statuses[:wait])
         end
        redirect_to admin_order_path(@order)
    end

    private
    def order_params
        params.require(:order).permit(:customer_id, :freight, :payment_method, :ship_post_code, :ship_to_address, :ship_name, :total_due, :order_status)
    end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  private

  def after_sign_in_path_for(resource)
    admin_orders_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :telephone ])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @items = Item.search(params[:keyword])
    @keyword = params[:keyword]
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h3 class="my-3">ジャンル編集</h3>
      <%= form_with model:@genre,url: admin_genre_path(@genre.id), local:true do |f| %>
        <%= f.label :ジャンル名 %>
        <%= f.text_field :genre_name %>
        <%= f.submit "変更を保存", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
      <h3 class="my-3">ジャンル一覧・追加</h3>
      <%= form_with model:@newgenres,url: admin_genres_path, lacal:true do |f| %>
        <div class="form-group">
          <%= f.label :ジャンル名 %>
          <%= f.text_field :genre_name, placeholder: "ジャンル名" %>
          <%= f.submit "新規登録", class: 'btn btn-success' %>
        </div>
      <% end %>

      <table class="table">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.genre_name %></td>
            <td><%= link_to '編集する', edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <h3 class="my-3">商品編集</h3>
　    <%= form_with model: [:admin, @item], local:true do |f| %>
　    <div class="form-group row">
        <%= f.label :商品画像, class: "col-3" %>
        <%= f.attachment_field :image, class: "col-7" %>
      </div>
      <div class="form-group row">
        <%= f.label :商品名, class: "col-3" %>
        <%= f.text_field :item_name, class: "form-control col-7" %>
      </div>
      <div class="form-group row">
        <%= f.label :商品説明, class: "col-3" %>
        <%= f.text_area :introduction, class: "form-control col-7" %>
      </div>
      <div class="form-group row">
        <%= f.label :ジャンル名, class: "col-3" %>
        <%= f.collection_select :genre_id, Genre.all, :id, :genre_name, prompt: "選択してください", class: "col-7" %>
      </div>
      <div class="form-group row">
        <%= f.label :税抜価格, class: "col-3" %>
        <%= f.text_field :price, class: "form-control col-7" %>
        <p class="col-1">円</p>
      </div>
      <div class="form-group row">
        <%= f.label :販売ステータス, class: "col-4" %>
        <div class="col-7">
          <%= f.label :販売中 %>
          <%= f.radio_button :is_status, true %>
          <%= f.label :販売停止 %>
          <%= f.radio_button :is_status, false %>
        </div>
      </div>
      <div class="form-group">
      <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class='container'>
  <div class='row'>
    <h3 class="col-8 mt-3 ">商品一覧</h3>
    <i class='col-4 mt-3  text-right'><%= link_to '', new_admin_item_path, class: "fas fa-plus-circle text-right" %></i>
  </div>
  <table class='table table-hover '>
  　<thead>
    <tr>
      <th class="col-1">商品ID</th>
      <th class="col-3">商品名</th>
      <th class="col-2">税抜価格</th>
      <th class="col-2">ジャンル</th>
      <th class="col-2">販売ステータス</th>
    </tr>
    </thead>
    <tbody>
    <% @items.each do |item| %>
    　<tr>
        <td><%= item.id %></td>
        <td><%= link_to item.item_name, admin_item_path(item) %></td>
        <td><%= (item.price).to_s(:delimited) %></td>
        <td><%= item.genre.genre_name %></td>
        <td>
        　<% if item.is_status == true %>
        　販売中
          <% else %>
          販売停止中
          <% end %>
      　</td>
      </tr>
    <% end %>
    </tbody>
  </table>
<%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class='container'>
  
  <% if @item.errors.any? %>
       <p class="my-3 text-danger">空白を埋めてください！！！</p>
  <% end %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <h3 class="my-3">商品新規登録</h3>
　    <%= form_with model: [:admin, @item], local:true do |f| %>
　    <div class="form-group row">
        <%= f.label :商品画像, class: "col-3" %>
        <%= f.attachment_field :image, class: "form col-7" %>
      </div>
      <div class="form-group row">
        <%= f.label :商品名, class: "col-3" %>
        <%= f.text_field :item_name, class: "form-control col-7" %>
      </div>
      <div class="form-group row">
        <%= f.label :商品説明, class: "col-3" %>
        <%= f.text_area :introduction, class: "form-control col-7" %>
      </div>
      <div class="form-group row">
        <%= f.label :ジャンル名, class: "col-3" %>
        <%= f.collection_select :genre_id, Genre.all, :id, :genre_name, prompt: "選択してください", class: 'form-control col-7' %>
      </div>
      <div class="form-group row">
        <%= f.label :税抜価格, class: "col-3" %>
        <%= f.text_field :price, class: "form-control col-7" %>
        <p class="col-1"円></p>
      </div>
      <div class="form-group row">
        <%= f.label :販売ステータス, class: "col-4" %>
        <div class="col-7">
          <%= f.label :販売中 %>
          <%= f.radio_button :is_status, true %>
          <%= f.label :販売停止 %>
          <%= f.radio_button :is_status, false %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit '新規登録', class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
　</div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h3 class="my-3">商品詳細</h3>
  <div class="row">
    <div class="col-lg-4 col-md-12 mx-auto">
      <%= attachment_image_tag @item, :image, :fill,300,200  %>
    </div>
    <div class="col-lg-8 col-md-12 mx-auto">
      <table class="table table-borderless">
        <tr>
          <th>商品名</th>
          <td><%= @item.item_name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.genre_name %></td>
        </tr>
        <tr>
          <th>税込価格<br>（税抜価格）</th>
          <td><%= @item.add_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>)</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td><% if @item.is_status == true %>販売中<% else %>販売停止<% end %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col text-center">
      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success center-block " %>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class='container'>
  <h3 class="my-3 ">注文履歴一覧</h3>
  <table class='table table-hover'>
    <thead>
    <tr>
      <th class="col-2">購入日時</th>
      <th class="col-2">購入者</th>
      <th class="col-2">購入個数</th>
      <th class="col-2">注文ステータス</th>
    </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %></td>
          <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
          <!--quantityは３桁で区切る-->
          <td><%= order.order_items.sum(:quantity) %></td>
          <td>
            <%if order.order_status == "shipped" %>
              <div class="text-success"><%= order.order_status_i18n %></div>
            <% else %>
              <%= order.order_status_i18n %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @orders %>
</div>

app/views/admin/orders/show.html.erb
<div class='container'>
  <h3 class="my-3">注文履歴詳細</h3>
  <div class="row">
    <table class="table table-borderless">
　    <tr>
        <th>購入者</th>
        <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <th>配送先</th>
         <td>〒<%= @order.ship_post_code %>　　<%= @order.ship_to_address %><br><%= @order.ship_name %></td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td><%= form_with model: [:admin, @order], local: :true do |f| %>
            <%= f.select :order_status, Order.order_statuses.keys.map { |k| [I18n.t("enums.order.order_status.#{k}"), k]},class: "prefecture-select " %>
            <%= f.submit '更新', class: "btn btn-success " %>
            <% end %>
        </td>
      </tr>
      <tr>
        <th>支払い方法</th>
        <td><%= @order.payment_method_i18n %></td>
      </tr>
    </table>
  </div>
  <div class="row">
    <div class="col-8">
      <table class="table table-hover">
        <tr>
          <th>商品名</th>
	        <th>単価(税込)</th>
	        <th>数量</th>
	        <th>小計</th>
	        <th>制作ステータス</th>
	        <th></th>
        </tr>
        <% @order.order_items.each do |order_item| %>
        <tr>
	        <td><%= order_item.item.item_name %></td>
	        <!--delimitedは３桁で区切る-->
	        <td><%= ((order_item.item.price * 1.1).floor).to_s(:delimited) %></td>
	        <td><%= order_item.quantity %></td>
	        <td><%= (((order_item.item.price * 1.1).floor) * order_item.quantity).to_s(:delimited) %></td>
          <td>
	          <%= form_with model: order_item, url: admin_order_order_item_path(@order,order_item), local: true do |f| %>
	          <%= f.select :sales_order_status, OrderItem.sales_order_statuses.keys.map { |k| [I18n.t("enums.order_item.sales_order_status.#{k}"), k] }, class:"form-control form-control-sm col-6" %>
          </td>
          <td><%= f.submit '更新', class: "btn btn-success " %><% end %></td>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="col-3 table table-borderless mt-5 ml-5">
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= (@order.total_due - @order.freight).to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.freight %>円</td>
        </tr>
        <tr>
          <th>請求合計</th>
          <td><%= (@order.total_due).to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>