config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  namespace :public do
    get 'genres/show'
  end
  get 'search' => 'searches#search'
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customer,skip: [:passwords,], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :items,except: [:destroy]
    resources :customers, except: [:destroy, :create, :new]
    resources :genres, except: [:destroy, :show, :new]
    get '/' => 'homes#top'
    resources:orders, only: [:index, :show, :update] do
      resources:order_items, only: [:update]
    end
  end

  scope module: :public do
    resources :customers, except: [:destroy]
    get '/' => 'homes#top'
    get '/about' => 'homes#about'
    resources :genres, only: [:show]
    patch 'unsubscribe' => 'customers#unsubscribe'
    get 'confirm' => 'customers#confirm'
    resources :items, only: [:index, :show]
    resources :cart_items, except: [:edit, :new, :show]
    delete 'destroy_all' => 'cart_items#destroy_all'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, except: [:destroy, :edit]
    resources :addresses, except: [:new, :show]
  end




end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    "〒" + self.post_code + " " + self.address + " " + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy

  validates :is_deleted, inclusion: { in: [true, false] }

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :genre_name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  attachment :image
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  belongs_to :genre


# 消費税の計算
  def add_tax_price
    (self.price * 1.1).round
  end

  # 検索機能
  def self.search(keyword)
    @items = Item.where("item_name LIKE ?", "%#{keyword}%")
  end


  validates :image, presence: true
  validates :item_name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  validates :is_status, presence: true

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: { wait: 0, check: 1, making: 2, prepare: 3, shipped: 4 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :item
  belongs_to :order

  enum sales_order_status: {
 impossible:0, wait:1, making:2, done:3
  }


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def index
    @newgenres = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
    redirect_to admin_item_path(@item)
    else
    render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end


  private

  def item_params
    params.require(:item).permit(:genre_id, :item_name, :introduction, :price, :image, :is_status, )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :telephone ])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @items = Item.search(params[:keyword])
    @keyword = params[:keyword]
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
          <div class="container">
            <a class="navbar-brand p-1" href="/"><%= image_tag 'nagano_cake_logo.png', :size => '230x50' %></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <% if customer_signed_in? %>
               <span style="color:white">ようこそ<%= current_customer.last_name %><%= current_customer.first_name %>さん！</span>
              <% end %>
              <ul class="navbar-nav ml-auto">
                <% if customer_signed_in? %>
                  <li><%= link_to "マイページ", customer_path(current_customer), class: 'nav-link active' %></li>
                  <li><%= link_to "商品一覧", items_path, class: 'nav-link active' %></li>
                  <li><%= link_to "カート", cart_items_path, class: 'nav-link active' %></li>
                  <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link active' %></li>
                <% elsif admin_signed_in? %>
                  <li><%= link_to "商品一覧", admin_items_path, class: 'nav-link active' %></li>
                  <li><%= link_to "会員一覧", admin_customers_path, class: 'nav-link active' %></li>
                  <li><%= link_to "注文履歴一覧", admin_orders_path, class: 'nav-link active' %></li>
                  <li><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link active' %></li>
                  <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link active' %></li>
                <% else %>
                  <li><%= link_to "About", about_path, class: 'nav-link active' %></li>
                  <li><%= link_to "商品一覧", items_path, class: 'nav-link active' %></li>
                  <li><%= link_to "新規登録", new_customer_registration_path, class: 'nav-link active' %></li>
                  <li><%= link_to "ログイン", new_customer_session_path, class: 'nav-link active' %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="search-form">
            <%= form_with url: search_path, method: :get, local:true do |f| %>
              <%= f.text_field :keyword, placeholder: "Search" %>
              <!--<%= f.submit %>-->
            <% end %>
          </div>
        </nav>
      </header>
      <%= yield %>
      <footer class=" footer mt-5">
        <p class="text-white text-center pt-3">©︎NAGANO CAKE</p>
      </footer>
    </div>
  </body>
</html>